### ISSUE TITLE
Usage/config question

### ISSUE THREAD

**Issue by DirkLachowski** [leojh/ember-deploy-rest-index#3]
I'm trying to use ember-deploy-rest-index with ember-cli 0.2.5 and am getting strange results.

I've deployed a mock REST-Server that implements the three endpoints and responds with a list with two revisions on the GET endpoint.

Doing a `deploy:list` gets me 

```
lacho$ ember deploy:list
version: 0.2.5
GET 'http://localhost:8080/api/revisions' to get revisions
Your revisions: 
TypeError: undefined is not a function
```

and a `ember deploy:activate ember-app:123456` gets me

```
lacho$ ember deploy:activate ember-app:123456
version: 0.2.5
PUT 'http://localhost:8080/api/revisions/undefined' to activate revision
Revision undefined was activated
```

What am i missing? Is ember-cli 0.2.5 to old to be used with ember-deploy?

**Comment by leojh** [comment]
Dirk, I'm not sure if 0.2.5 is too old to use.... it may be? I didn't think about setting up a mock server to test this adapter, this is a great idea. Can you push your code up somewhere so I can take a look and see where it's breaking?

**Comment by DirkLachowski** [comment]
Sure, have a look at DirkLachowski/ember-deploy-rest-index-server/commit/a4c8916c1fb744dfb59dfefae48d579de3aa092f

**Comment by DirkLachowski** [comment]
Sure, have a look at  DirkLachowski@a4c8916c1fb744dfb59dfefae48d579de3aa092f 

But if you look at the output i get for a `deploy:activate` then this is in no way server related. I am giving a (fake) revision to activate and the plugin is `PUT`ing a revision of `undefined`.

**Comment by leojh** [comment]
Alright, with the GET call (and for all other calls for that matter) you have to specify the environment flag on your command. This is actually a limitation of ember-deploy. So, try doing this: `ember deploy:list --environment development`

With the PUT, same thing, try specifying the environment PLUS you also have to specify the revision using the revision flag. Like this: `ember deploy:activate --revision ember:1234 --environment development`

I will update the docs to make this more clear. Also, if you're on the ember slack community, feel free to look me up under leojh

**Comment by DirkLachowski** [comment]
Thanks for the tip but i've already tried that before. After upgrading to the latest ember-cli at least activating now works, but `deploy:list`still shows the same error.

**Comment by DirkLachowski** [comment]
I've added some debug output to the `_list` function. Looks as if the node rest client fails on parsing the response. If i execute a `deploy:list` against the mock server (giving me a response with two revisions) the data received from the rest client seems to be a string and not an array.

Given

```
_list: function() {
return new Promise(function(resolve, reject) {
  var path = this._buildPath();

  this._writeLineInGreen("GET '" + path + "' to get revisions");
  this._writeEmptyLine();

  this.client.get(path, function(data, response) {
    this._writeLineInGreen("status: " + response.statusCode);
    this._writeLineInGreen("data: " + data[0]);
```

with a server response of

```
[
    {"id":"ember-app:1bdc67a","createdOn":"2015-06-19T09:58:00-04:00"},
    {"id":"ember-app:1bdc67b","createdOn":"2015-06-29T09:58:00-04:00"}
]
```

the last `writeLine` outputs `91` (decimal for `[`) and not the first object from the response.
My node rest client is at the latest version.

If i change `_list` to

```
_list: function() {
return new Promise(function(resolve, reject) {
  var path = this._buildPath();

  this._writeLineInGreen("GET '" + path + "' to get revisions");
  this._writeEmptyLine();

  this.client.get(path, function(data, response) {
    data = JSON.parse(data);
```

Everything works as expected.

**Comment by DirkLachowski** [comment]
I think i've found the problem. node-rest-client seems to be very picky regarding the submitted response type.

You are registering

```
mimetypes: {
    json:["application/json","application/json; charset=utf-8"]
  }
```

but my server sends the following headers (outputted from the raw response the client receives)

```
{
"server": "Apache-Coyote/1.1",
"x-application-context": "cobai-appstore:8080",
"content-type": "application/json;charset=UTF-8",
"transfer-encoding": "chunked",
"date": "Sat, 05 Sep 2015 13:14:57 GMT",
"connection": "close"
}
```

Notice the missing space between the semicolon and the charset definition. If i change your client registration like so

```
this.client = new Client({
  mimetypes: {
    json:["application/json","application/json; charset=utf-8","application/json;charset=utf-8"]
  }
});
```

the error is gone.

**Comment by leojh** [comment]
Perfect. Do a PR for whatever changes you have so we can make this better. One important thing that's missing from the adapter is passing a security token in a header to authenticate. I'll have some time this weekend to work on this.

**Comment by leojh** [comment]
Fixed with commit https://github.com/leojh/ember-deploy-rest-index/commit/197b7c229274811a8dd4ecade598806122a6d5d3
